name: skip CI

on:
  push:
    branches:
      - skip-ci
  pull_request:
    branches:
      - skip-ci

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]') && !contains(toJSON(github.event.pull_request), '[skip pr]')"
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{toJSON(github.event)}}'
      - run: echo '${{toJSON(github.event.commits.*.message)}}'
      - run: echo '${{toJSON(github.event.pull_request)}}'
      - run: echo '${{join(toJSON(github.event.commits.*.message), toJSON(github.event.pull_request))}}'
      - run: echo '${{format('{0}{1}', toJSON(github.event.commits.*.message), toJSON(github.event.pull_request))}}'
      - run: echo '${{!contains(toJSON(github.event.commits.*.message), '[skip ci]')}}'
      - run: echo '${{!contains(format('{0}{1}', toJSON(github.event.commits.*.message), toJSON(github.event.pull_request)), '[skip ci]')}}'
